/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module App {
    /** Generated from Sam.DbContext.Area **/
    export interface IArea extends App.IEntityObjectBaseId {
        Name: string;
        BuildingId: string;
        Building: App.IBuilding;
        OwnerId: string;
        Owner: any;
    }
    /** Generated from Sam.DbContext.Building **/
    export interface IBuilding extends App.IEntityObjectBaseId {
        Name: string;
        Address1: string;
        Address2: string;
        CityId: string;
        City: App.ICity;
        OwnerId: string;
        Owner: any;
    }
    /** Generated from Sam.DbContext.City **/
    export interface ICity extends App.IEntityObjectBaseId {
        Name: string;
        ZipCode: string;
        CountryId: string;
        Country: App.ICountry;
    }
    /** Generated from Sam.DbContext.Country **/
    export interface ICountry extends App.IEntityObjectBaseId {
        Name: string;
    }
    /** Generated from Sam.DbContext.EntityObjectId<TKey> **/
    export interface IEntityObjectBaseId {
        Id: any;
        CreatedDate: string;
        CreatedById: string;
        CreatedBy: any;
        ModifiedDate: string;
        ModifiedById: string;
        ModifiedBy: any;
    }
    /** Generated from Sam.DbContext.EntityObjectId **/
    export interface IEntityObjectId extends App.IEntityObjectBaseId {
    }
    /** Generated from Sam.DbContext.Company **/
    export interface ICompany extends App.IEntityObjectBaseId {
        Name: string;
        ZipCode: string;
        Address1: string;
        Address2: string;
        CustomerId: string;
        Customer: App.ICustomer;
    }
    /** Generated from Sam.DbContext.Customer **/
    export interface ICustomer extends App.IEntityObjectBaseId {
        Name: string;
    }
    /** Generated from Sam.DbContext.Department **/
    export interface IDepartment extends App.IEntityObjectBaseId {
        Name: string;
        CompanyId: string;
        Company: App.ICompany;
    }
    /** Generated from Sam.DbContext.Employee **/
    export interface IEmployee extends App.IEntityObjectBaseId {
        Name: string;
        Email: string;
        PinCode: number;
        Status: any;
        Image: string;
        DepartmentId: string;
        ManagerId: string;
        UserId: string;
    }
    /** Generated from Sam.DbContext.TypeScriptUser **/
    export interface IUser {
        Id: string;
        UserName?: string;
        PasswordHash?: string;
        Email?: string;
    }
}
